### ISSUE TITLE
Test part of multi label

### ISSUE THREAD

**Issue by jyuan1118** [miraclewkf/multilabel-MXNet#1]
Hi, thanks for your multi label code. It runs well. Just wondering, are you have the code of multi label testing part?  thanks a lot.

**Comment by miraclewkf** [comment]
Maybe later, you can watch or star this project for update information. Thanks.

**Comment by jyuan1118** [comment]
I wrote a testing code for this project. Just not sure it works well or not. 
I appreciate it if you have time to check it, thanks.
I set number of classes to 625.

`sym, arg_params, aux_params = mx.model.load_checkpoint(
        './models/resnet-101', 60)
    mod = mx.mod.Module(symbol=sym, context=devs)
    mod.bind(for_training=False, data_shapes=[('data', (1,3,224,224))],
        label_shapes=[('softmax_label',(1,625))])
    mod.set_params(arg_params, aux_params)`

Read image and transfer to array, then

`mod.forward(Batch([array]), is_train=False)
    prob = mod.get_outputs()[0].asnumpy()`

pro is the output of prediction.

**Comment by miraclewkf** [comment]
You are wright. In this line `mod.forward(Batch([array]), is_train=False)`, `Batch()` can be replace by `mx.io.DataBatch()`

**Comment by jyuan-git** [comment]
But the result is not correct. I am confusing why the predictions of all images are same. 
Did you have any suggestion about the testing? Thanks.

**Comment by jyuan-git** [comment]
Why are you set the actually calculate loss to 'False' in the forward function ? 
`    def forward(self, is_train, req, in_data, out_data, aux):`
        `# Shapes:`
        `#  b = minibatch size`
        `#  d = number of dimensions`
        `actually_calculate_loss = False`
        `if actually_calculate_loss:`
        `    p = in_data[0].asnumpy()  # shape=(b,d)`
        `    y = in_data[1].asnumpy()`
        `    out = y * np.log(p+self.eps) + (1.-y) * np.log((self.eps1) - p)`
        `    self.assign(out_data[0], req[0], mx.nd.array(out))`
        `else:`
        `    # Just copy the predictions forward`
        `   self.assign(out_data[0], req[0], in_data[0])`

**Comment by miraclewkf** [comment]
If the prediction of all examples are the same, maybe you should check your input first. Then, check your class number and output predication.

**Comment by g2ragrawal** [comment]
can someon please provide example to test with image @miraclewkf  @jyuan1118 
i am trying but getting this error
TypeError: __new__() missing 1 required positional argument: 'softmax_label'
or this
AttributeError: 'Batch' object has no attribute 'label'

**Comment by g2ragrawal** [comment]
```
def model_load(): 
    sym, arg_params, aux_params = mx.model.load_checkpoint('multilabelresnet50', 4)
    print(arg_params)
    mod = mx.mod.Module(symbol=sym)
    mod.bind(for_training=False, data_shapes=[('data', (1,3,224,224))], label_shapes=[('softmax_label',(1,4))])
    mod.set_params(arg_params, aux_params,allow_missing=True)
    return mod

def predict(array, model):
    Batch = namedtuple('Batch', ['data'])
    model.forward(Batch([array]),is_train=False)
    prob = model.get_outputs()[0].asnumpy()
    return prob
if __name__=='__main__':
    img = image.imread('b.jpg')
    img = transform_eval(img)
    print((img.shape))
    model=model_load()
    v1=predict(img,model)
    print(v1)
```
i am using this and getting error 
AttributeError: 'Batch' object has no attribute 'label'
@miraclewkf can you help please

**Comment by g2ragrawal** [comment]
@jyuan1118 how did you solve the problem of same output?
